### ISSUE TITLE
reduce the dependencies in the requirements file to let only the core one

### ISSUE THREAD

**Issue by jfunez** [blurg/sauron-engine#130]
**Is your feature request related to a problem? Please describe.**
Large amount of dependencies produce more work to maintain dependencies up-to-date (even with pyup, PRs need to be merged.

**Describe the solution you'd like**
reduce the dependencies listed in requirements file, in order to have less PRs from PyUP

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by jlugao** [comment]
In theory all we need is the dependencies listed on [pyproject.toml](https://github.com/blurg/sauron-engine/blob/master/pyproject.toml#L15) for production. Is there a tool to help with this conversion? We could also do it manually

**Comment by jlugao** [comment]
I'll take this
