### ISSUE TITLE
Programmatic Generation of Rules

### ISSUE THREAD

**Issue by jlugao** [blurg/sauron-engine#29]
We are creating a very nice json format for the rules. However, if I wanted to automate a process using scripts only generating those json would be quite cumbersome. 

I believe that we could aim to something like this:

```python
engine = RuleEngine()
rule = Rule()
rule.add_condition("condition_name", arg1, arg2)
rule.add_action("action_name", arg1, arg2)

engine.run(rule)
```

**Comment by jlugao** [comment]
Not sure if we should put this on 1.0

**Comment by jlugao** [comment]
Ok, now we can use yaml and I believe that manually writing rules is not that much of a deal anymore. We can still do this but I think that a yaml should be generated and exported. 

This however is very low priority now

**Comment by jfunez** [comment]
example with simple jobs (no rule engine)
```python
engine = Engine()
rule = Rule()

rule.add_job("job_name_1", arg1, arg2)
rule.add_job("job_name_2", arg3, arg4)

engine.run(rule)
```
