### ISSUE TITLE
Project dead? 

### ISSUE THREAD

**Issue by KrunchMuffin** [blurg/sauron-engine#297]
I was looking for a rules engine in Python, and I found this. Looked very interesting and the fact that it's influenced by fast API is a big bonus given that's what I am using. I See there hasn't been much action on this repo, so I'm wondering if it is still alive? I hope so.

**Comment by jlugao** [comment]
Hey @KrunchMuffin the project is alive, but it has been hard to make time for it lately. We have plans to continue improving the project and will make a sprint to develop a couple more features and update the docs soon. 

Feel free to use the project, contribute, ask questions, and open issues. I hope you enjoy using it as much as I do.
